matrix:
  GO_VERSION:
    - 1.8
    - 1.8.3
    
workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - cd /workspace/sample-helloworld
      - make build
      - make test
