workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    commands: 
      - ls
      - cat ~/.netrc

pipeline:
  build:
    image: index.qiniu.com/spock/golang:${IMG_TAG}
    commands:
      - curl -s http://spock.dev.qiniu.io/assets/env.sh -o env.sh && source ./env.sh
      - cd /workspace/sample-helloworld
      - make build
      - make test

  publish:
    image: index.qiniu.com/spock/docker-client
    commands:
      - curl -s http://spock.dev.qiniu.io/assets/env.sh -o env.sh && source ./env.sh
      - echo $SERVICE
      - echo $TAG
      - echo Test
  
  archive:
    image: index.qiniu.com/spock/kodo-plugin
    pull: true
    source: /workspace/sample-helloworld/go/demo
    key: demo-[SERVICE]-[TAG]
    delete: true
    secrets: [BUCKET_USER, BUCKET_PWD]
    
